# site settings
title: tuhex station
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme #
email:
description: >-
  game design
domain: tuhex.github.io
url: https://tuhex.github.io
baseurl: 
